variable "mod_vpc1_cidr_block" {}
variable "mod_vpc1_id" {}
variable "mod_vpc1_pubsn_count" {}
variable "mode_vpc1_pubsn_ids" {}
variable "mod_vpc1_public_cidr_block" {}
variable "mod_avz" {}
variable "mode_cassandra_cluster_instances_count" {}
variable "mod_ami" {}
variable "mod_cassandra_node_instance_type" {}
variable "mod_cassandra_key_name" {}
variable "mod_vpc1_cassandra_sg_name" {}